config/routes.rb
Voterize::Application.routes.draw do
  devise_for :voters

  resources :voters
  resources :candidates

  root :to => "voters#index"

  match 'vote_now' => 'voters#vote_now'
  

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :name

  has_many	:votes, :dependent => :destroy

  


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # attr_accessible :title, :body

 attr_accessible 	:candidate_id

belongs_to :voter
belongs_to :candidate



end

app/models/voter.rb
class Voter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

	attr_accessible 	:name,
  						:vote_attributes

  	has_one	:vote, :dependent => :destroy

	accepts_nested_attributes_for	:vote



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  before_filter :authenticate_voter!
  before_filter :check_admin


  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @candidates }
    end
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/new
  # GET /candidates/new.json
  def new
    @candidate = Candidate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @candidate }
    end
  end

  # GET /candidates/1/edit
  def edit
    @candidate = Candidate.find(params[:id])
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(params[:candidate])

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render json: @candidate, status: :created, location: @candidate }
      else
        format.html { render action: "new" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /candidates/1
  # PUT /candidates/1.json
  def update
    @candidate = Candidate.find(params[:id])

    respond_to do |format|
      if @candidate.update_attributes(params[:candidate])
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy

    respond_to do |format|
      format.html { redirect_to candidates_url }
      format.json { head :no_content }
    end
  end
end

private

  def check_admin
    if current_voter.administrator == true
      @message = "You can manage candidates"
      @cleared_to_create = true
    else
      @message = "You are not allowed to manage candidates"
      @cleared_to_create = false
    end
  end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  # GET /voters
  # GET /voters.json


before_filter :authenticate_voter!, :except => "index"


  def vote_now

    @voter = current_voter

    @voter.build_vote # this is to let the form assign a vote

    @candidates = Candidate.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @voter }
    end


  end

  def index

    @voters = Voter.all

    @votes = Vote.all
    @candidates = Candidate.all

    if  Vote.count == 0
      @winner = "No votes cast so no winners yet."
    
    else

      # the following finds the winning candidate
      # First, reduce the votes to an array of candidate_ids

      votecount = Vote.all.map {|vote| vote.candidate_id}

      # Now, do something with inject that creates a hash, one key per candidate,
      #   and the value is the count of occurrences of that candidate_id

      freq = votecount.inject(Hash.new(0)) { |h,v| h[v] += 1; h}
      
      # Now, sort by the frequency matched by that key, and use the result
      # (the highest-ferquency candidate_id) to 'find' the name of the candidate

      @winner = "The winning candidate is " + Candidate.find(votecount.sort_by { |v| freq[v]}.last).name

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @voters }
    end

  end

  # GET /voters/1
  # GET /voters/1.json
  def show
    @voter = Voter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @voter }
    end
  end

  # GET /voters/new
  # GET /voters/new.json
  
  # def new

  #   @voter = Voter.new

  #   @voter.build_vote # this is to let the form assign a vote

  #   @candidates = Candidate.all

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @voter }
  #   end
  # end

  # GET /voters/1/edit
  def edit
    @voter = Voter.find(params[:id])

    @candidates = Candidate.all
    
  end

  # POST /voters
  # POST /voters.json
  def create
    @voter = Voter.new(params[:voter])

    respond_to do |format|
      if @voter.save
        format.html { redirect_to @voter, notice: 'Voter was successfully created.' }
        format.json { render json: @voter, status: :created, location: @voter }
      else
        format.html { render action: "new" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /voters/1
  # PUT /voters/1.json
  def update
    @voter = Voter.find(params[:id])

    respond_to do |format|
      if @voter.update_attributes(params[:voter])
        format.html { redirect_to @voter, notice: 'Voter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voters/1
  # DELETE /voters/1.json
  def destroy
    @voter = Voter.find(params[:id])
    @voter.destroy

    respond_to do |format|
      format.html { redirect_to voters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/voters_helper.rb
module VotersHelper
end

app/views/candidates/_form.html.erb
<%= form_for(@candidate) do |f| %>
  <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% @candidate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= @message %>

  <% if @cleared_to_create == true %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render 'form' %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>



<% @candidates.each do |candidate| %>
  
  <%= candidate.name %><br />
    
<% end %>


<br />

<%= link_to 'New Candidate', new_candidate_path %>
<br /><br />

<%= link_to 'Main voter page', voters_path %>


<p class = "helper">To add a candidate, the user must have the boolean attribute 'administrator' set to true. There is no browser interface to set this attribute, it must be done through the console. In the instance of the application running on Heroku as growing-sky-7466, the account tom@tom.com (password = progfun) can add candidates.</p>

app/views/candidates/new.html.erb
<h1>New candidate</h1>

<%= render 'form' %>

<%= link_to 'List of candidates', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @candidate.name %>
</p>


<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voterize</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<% if current_voter.nil? %>
	<p class="notice">You are not signed in. <%= link_to "Sign in." , voter_session_path%></p>
	<% else %>
 	<p class="notice">You are signed in as: <%= current_voter.email %></p>
 	<%= link_to "Sign out", destroy_voter_session_path, :method => :delete %>
 	<% end %>

<%= yield %>

</body>
</html>

app/views/voters/_form.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

    <h2>Here comes the voting section</h2>

    <div class="field">

      
        <%= f.fields_for :vote do |vote| %>

        <% @candidates.each do | candidate | %>
            
            <%= vote.radio_button :candidate_id , candidate.id %>
            <%= vote.label :candidate_id, candidate.name %>
            <br>
            
            <% end %>

        <% end %>

    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voters/edit.html.erb
<h1>Editing voter</h1>

<%= render 'form' %>

<%= link_to 'Show', @voter %> |
<%= link_to 'Back', voters_path %>

app/views/voters/index.html.erb
<link rel = "stylesheet" type = "text/css" href = "../../assets/stylesheets/application.css">



<h2>The voter roll</h2>
<p class = "helper">I added this section because it helped me remember what usernames I had registered. If you are logged in, a link to vote, or to see your vote if you've voted already, appears next to your name.</p>

<% if current_voter.nil? %>
<% logged_in_id = 0 %>
<% else logged_in_id = current_voter.id %>
<% end %>

<% @voters.each do |voter| %>
  
    <%= voter.email %>

    <% if voter.id == logged_in_id %>

      <% if voter.vote.nil? %>
      <%= link_to 'Vote now', vote_now_path %><br />
      <% else %>

        <%= link_to 'See how you voted', voter %><br />
      <% end %>
      <% else %> <br>
    <% end %>

<% end %>


<br />

<h2>The Results</h2>


<table>

  <% totalvotes = @votes.count %>

<% if totalvotes > 0 %>

<% @candidates.each do |candidate| %>
  <% votecount = @votes.count {|vote| vote.candidate_id == candidate.id } %> 

  <tr>
    <td><%= candidate.name %></td>
    <td><%= votecount %> votes</td>
    <td><%= 100 * votecount/totalvotes %> percent</td>
 </tr>

<% end %>

</table>

<% end %>  <!-- end of the if test for whether votes have been cast -->

<p><%= @winner %></p>

<br>

<%= link_to 'Add a candidate', new_candidate_path %>

app/views/voters/new.html.erb
<h1>New voter</h1>

<%= render 'form' %>

<%= link_to 'Back', voters_path %>

app/views/voters/show.html.erb
<p id="notice"><%= notice %></p>


<p>

	<b>Your Vote</b><br>

	<table>
		<tr><td>Candidate #</td><td><%=	@voter.vote.candidate_id %></td></tr>

		<tr><td>Candidate Name</td><td><%=	@voter.vote.candidate.name %></td></tr>

		<tr><td>Vote time</td><td><%= @voter.vote.updated_at.asctime %></td></tr>
	</table>

</p>


<%= link_to 'Back', voters_path %>

app/views/voters/vote_now.html.erb
<%= form_for(@voter) do |f| %>
  <% if @voter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voter.errors.count, "error") %> prohibited this voter from being saved:</h2>

      <ul>
      <% @voter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <h2>Please select your candidate</h2>

    <div class="field">

      
        <%= f.fields_for :vote do |vote| %>

        <% @candidates.each do | candidate | %>
            
            <%= vote.radio_button :candidate_id , candidate.id %>
            <%= vote.label :candidate_id, candidate.name %>
            <br>
            
            <% end %>

        <% end %>

    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>